/**
 * Flashcards API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthControllerTestProtectedRoute200ResponseUser { 
    id?: string;
    email?: string;
}

