/**
 * Flashcards API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthControllerTestProtectedRoute200ResponseUser } from './authControllerTestProtectedRoute200ResponseUser';


export interface AuthControllerTestProtectedRoute200Response { 
    message?: string;
    user?: AuthControllerTestProtectedRoute200ResponseUser;
}

