/**
 * Flashcards API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface User {
  id: string
  email: string
  firstName: string
  lastName: string
  profilePicture: string
  provider: string
  createdAt: string
  updatedAt: string
}
